name       : jack-capture
version    : 0.9.73
release    : 3
source     :
    - https://github.com/kmatheussen/jack_capture/archive/0.9.73.tar.gz : 21afb0257ed7437708cc9e5bec2f6299599461b7eec8bf66967d8ecadb0751de
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A program for recording soundfiles with jack.
description: |
    Jack_capture is a program for recording soundfiles with jack.
builddeps  :
    - pkgconfig(jack)
    - pkgconfig(liblo)
    - pkgconfig(sndfile)
    - lame-devel
    - zenity
build      : |
    %make
install    : |
    %make_install PREFIX=/usr

    # Install the gtk2 gui
    install -Dm00755 jack_capture_gui $installdir/usr/bin/jack_capture_gui
